name: CICD

on: 
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} || exit 1
        
      - name: Build Docker image
        run: docker build -t drjseifu/nodejs-app . || exit 1
        
      - name: Publish image to Docker Hub
        run: docker push drjseifu/nodejs-app:latest || exit 1
      
  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from Docker Hub
        run: docker pull drjseifu/nodejs-app:latest || exit 1
        
      - name: Delete old container (if exists)
        run: docker rm -f nodejs-app-container || true  # Ignore error if the container doesn't exist
        
      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name nodejs-app-container drjseifu/nodejs-app || exit 1

  notify:
    runs-on: ubuntu-latest
    needs: [build, deploy]
    if: ${{ always() }}
    steps:
      - name: Check build job status
        id: build_status
        if: failure()
        run: echo "::set-output name=status::failed"
      
      - name: Check deploy job status
        id: deploy_status
        if: failure()
        run: echo "::set-output name=status::failed"

      - name: Send Telegram message on failure
        if: steps.build_status.outputs.status == 'failed' || steps.deploy_status.outputs.status == 'failed'
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="CI/CD process failed."

      - name: Send Telegram message on success
        if: steps.build_status.outputs.status != 'failed' && steps.deploy_status.outputs.status != 'failed'
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="Deployment completed successfully."
