name: CICD

on: 
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAMEE }} -p ${{ secrets.DOCKER_PASSWORD }} || exit 1
        
      - name: Build Docker image
        run: docker build -t drjseifu/nodejs-app . || exit 1
        
      - name: Publish image to Docker Hub
        run: docker push drjseifu/nodejs-app:latest || exit 1

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from Docker Hub
        run: docker pull drjseifu/nodejs-app:latest || exit 1
        
      - name: Delete old container (if exists)
        run: docker rm -f nodejs-app-container || true  # Ignore error if the container doesn't exist
        
      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name nodejs-app-container drjseifu/nodejs-app || exit 1

  notify:
    runs-on: ubuntu-latest
    if: always()
    needs: [build, deploy]
    steps:
      - name: Check if any job failed
        id: check_failure
        run: echo ::set-output name=failed::$(if [ ${{ job.status }} == 'failure' ]; then echo "true"; else echo "false"; fi)
      
      - name: Send Telegram message on failure
        if: steps.check_failure.outputs.failed == 'true'
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="CI/CD process failed."
      
      - name: Send Telegram message on success
        if: steps.check_failure.outputs.failed == 'false'
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="Deployment completed successfully."
